// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStylePublishFeedReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(upload_id,setUpload_id:)) NSString* JV2_PROP_NM(o,0,upload_id);

@end
