// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "FSStylePublishFeedRsp.h"

@implementation FSStylePublishFeedRsp

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(ret_msg) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.PublishFeedRsp";
}

@end
