// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    FSStyleFeedErrQcloudAuth = -20000
};
#define FSStyleFeedErrCode NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface FSStyleFeedErrCodeHelper: JceEnumHelper

+ (NSString *)etos:(FSStyleFeedErrCode)e;
+ (FSStyleFeedErrCode)stoe:(NSString *)s;

@end

#endif
