// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "FSStyleFeedErrCode.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation FSStyleFeedErrCodeHelper

+ (NSString *)etos:(FSStyleFeedErrCode)e
{
    switch(e){
        case FSStyleFeedErrQcloudAuth: return @"FSStyleFeedErrQcloudAuth";
        default: return @"";
    }
}

+ (FSStyleFeedErrCode)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"FSStyleFeedErrQcloudAuth")) return FSStyleFeedErrQcloudAuth;
    return NSIntegerMin;
}

@end

#endif
