// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStylePublishFeedRsp : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(ret_code,setRet_code:)) JceInt32 JV2_PROP_NM(o,0,ret_code);
@property (nonatomic, retain, JV2_PROP_GS_V2(ret_msg,setRet_msg:)) NSString* JV2_PROP_NM(o,1,ret_msg);

@end
