// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `Login.jce'
// **********************************************************************

#import "FSStyleRspLogin.h"

@implementation FSStyleRspLogin

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(ret_msg) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(ticket) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.RspLogin";
}

@end
