// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `Login.jce'
// **********************************************************************

#import "FSStyleReqLoginByWxCode.h"

@implementation FSStyleReqLoginByWxCode

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(code) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.ReqLoginByWxCode";
}

@end
