// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `Login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStyleRspLogin : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(ret_code,setRet_code:)) JceInt32 JV2_PROP_NM(o,0,ret_code);
@property (nonatomic, retain, JV2_PROP_GS_V2(ret_msg,setRet_msg:)) NSString* JV2_PROP_NM(o,1,ret_msg);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(o,2,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(ticket,setTicket:)) NSString* JV2_PROP_NM(o,3,ticket);

@end
