// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `Login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStyleReqLoginByQQToken : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(openid,setOpenid:)) NSString* JV2_PROP_NM(r,0,openid);
@property (nonatomic, retain, JV2_PROP_GS_V2(token,setToken:)) NSString* JV2_PROP_NM(r,1,token);

@end
