// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `Login.jce'
// **********************************************************************

#import "FSStyleReqLoginByQQToken.h"

@implementation FSStyleReqLoginByQQToken

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(openid) = DefaultJceString;
        JV2_PROP(token) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.ReqLoginByQQToken";
}

@end
