// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `Login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStyleReqLoginByWxCode : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(code,setCode:)) NSString* JV2_PROP_NM(r,0,code);

@end
