// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/Downloads/KiddyTest.jce'
// **********************************************************************

#import "QZJVacJsonReq.h"

@implementation QZJVacJsonReq

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(input) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"VAC.json_req";
}

@end
