// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/Downloads/KiddyTest.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface QZJVacJsonReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(input,setInput:)) NSString* JV2_PROP_NM(o,0,input);
@property (nonatomic, retain, JV2_PROP_GS_V2(input_list,setInput_list:)) NSArray* JV2_PROP_EX(o,1,input_list,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(input_map,setInput_map:)) NSDictionary* JV2_PROP_EX(o,2,input_map,M09ONSStringONSString);

@end
