// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "VACReportReq.h"
#if ! __has_feature(objc_arc)
#error This file must be compiled with ARC. Use -fobjc-arc flag (or convert project to ARC).
#endif

@implementation VACReportReq

#if JCE_USE_DYNAMIC_PROPERTY
@dynamic JV2_PROP_EX(r,0,reports,VOVACReportInfo);
#endif

#ifndef JCE_USE_DYNAMIC_INITIALIZATION
- (id)init
{
    if (self = [super init]) {
        JV2_PROP(reports) = DefaultJceArray;
    }
    return self;
}
#endif

+ (NSString*)jceType
{
    return @"MQQ.ReportReq";
}

@end
