// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface VACReportItem : JceObjectV2

// 关键步骤:  例如支付的步骤：payInvoke;parseUrl;payAuth;payAuthResult;callSDK;SDKCallback
@property (nonatomic, retain, JV2_PROP_GS_V2(step,setStep:)) NSString* JV2_PROP_NM(o,0,step);

// 每个步骤对应的耗时(单位ms).  例如： 658
@property (nonatomic, assign, JV2_PROP_GS_V2(costTime,setCostTime:)) JceInt64 JV2_PROP_NM(o,1,costTime);

// 记录关键步骤输入的相关参数。 如："apple_pay_source=1&app_id=3232"
@property (nonatomic, retain, JV2_PROP_GS_V2(params,setParams:)) NSString* JV2_PROP_NM(o,2,params);

// 结果,0:成功，-1:存储失败，-2：已存在
@property (nonatomic, assign, JV2_PROP_GS_V2(result,setResult:)) JceInt32 JV2_PROP_NM(o,3,result);

// 失败原因，如：系统抛出的Exception信息
@property (nonatomic, retain, JV2_PROP_GS_V2(failReason,setFailReason:)) NSString* JV2_PROP_NM(o,4,failReason);

@end
