// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "VACReportBody.h"
#if ! __has_feature(objc_arc)
#error This file must be compiled with ARC. Use -fobjc-arc flag (or convert project to ARC).
#endif

@implementation VACReportBody

#if JCE_USE_DYNAMIC_PROPERTY
@dynamic JV2_PROP_NM(o,0,sKey);
@dynamic JV2_PROP_NM(o,1,startTime);
@dynamic JV2_PROP_NM(o,2,totalTime);
@dynamic JV2_PROP_EX(o,3,reportItems,VOVACReportItem);
#endif

- (id)init
{
    if (self = [super init]) {
//        JV2_PROP(sKey) = DefaultJceString;
        JV2_PROP(startTime) = [[NSDate date] timeIntervalSince1970] * 1000;
        JV2_PROP(reportItems) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"MQQ.ReportBody";
}

@end
