// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "VACReportItem.h"

@interface VACReportBody : JceObjectV2

// 关键字,所有步骤对应的关键字，如：钱包的tokenId 等
@property (nonatomic, retain, JV2_PROP_GS_V2(sKey,setSKey:)) NSString* JV2_PROP_NM(o,0,sKey);
// 状态报告开始时间
@property (nonatomic, assign, JV2_PROP_GS_V2(startTime,setStartTime:)) JceInt64 JV2_PROP_NM(o,1,startTime);
// 总共耗时(单位ms) 例如：从支付入口开始到返回给第三方的所有时间
@property (nonatomic, assign, JV2_PROP_GS_V2(totalTime,setTotalTime:)) JceInt64 JV2_PROP_NM(o,2,totalTime);
// 一个统计上报的每个关键步骤统计
@property (nonatomic, retain, JV2_PROP_GS_V2(reportItems,setReportItems:)) NSArray* JV2_PROP_EX(o,3,reportItems,VOVACReportItem);

@end
