// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "VACReportInfo.h"

@interface VACReportReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(reports,setReports:)) NSArray* JV2_PROP_EX(r,0,reports,VOVACReportInfo);

@end
