// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "VACReportBody.h"
#import "VACReportHeader.h"

@interface VACReportInfo : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(header,setHeader:)) VACReportHeader* JV2_PROP_NM(r,0,header);
@property (nonatomic, retain, JV2_PROP_GS_V2(body,setBody:)) VACReportBody* JV2_PROP_NM(o,1,body);


- (instancetype)initWithModule:(NSString *)module action:(NSString *)action;
- (void)saveToDisk;
- (void)deleteFromDisk;
+ (NSMutableArray *)loadFromDisk;
+ (void)deleteFromDisk:(int64_t)seqNo;

@end
