// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "VACReportItem.h"

#if ! __has_feature(objc_arc)
#error This file must be compiled with ARC. Use -fobjc-arc flag (or convert project to ARC).
#endif

@implementation VACReportItem

#if JCE_USE_DYNAMIC_PROPERTY
@dynamic JV2_PROP_NM(o,0,step);
@dynamic JV2_PROP_NM(o,1,costTime);
@dynamic JV2_PROP_NM(o,2,params);
@dynamic JV2_PROP_NM(o,3,result);
@dynamic JV2_PROP_NM(o,4,failReason);
#endif

#ifndef JCE_USE_DYNAMIC_INITIALIZATION
- (id)init
{
    if (self = [super init]) {
        JV2_PROP(step) = DefaultJceString;
        JV2_PROP(params) = DefaultJceString;
        JV2_PROP(failReason) = DefaultJceString;
    }
    return self;
}
#endif

+ (NSString*)jceType
{
    return @"MQQ.ReportItem";
}

@end
