// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/eric/Documents/Projects/iPhoneQQ_6.0.0_VAC_wallet/Classes/ui/QQWallet/DataReport/JCE/VACDReport.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "VACReportHeader.h"

@interface VACReportRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(headers,setHeaders:)) NSArray* JV2_PROP_EX(r,0,headers,VOVACReportHeader);

@end
