// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/WNSPush.jce'
// **********************************************************************

#import "FSSrfWNSPushData.h"

@implementation FSSrfWNSPushData

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(push_cmd) = DefaultJceString;
        JV2_PROP(busi_content) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"srf.WNSPushData";
}

@end
