// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/WNSPush.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSSrfWNSPushData : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(push_cmd,setPush_cmd:)) NSString* JV2_PROP_NM(r,0,push_cmd);
@property (nonatomic, retain, JV2_PROP_GS_V2(busi_content,setBusi_content:)) NSString* JV2_PROP_NM(r,1,busi_content);
@property (nonatomic, assign, JV2_PROP_GS_V2(push_timestamp,setPush_timestamp:)) JceInt64 JV2_PROP_NM(r,2,push_timestamp);
@property (nonatomic, assign, JV2_PROP_GS_V2(expire_timestamp,setExpire_timestamp:)) JceInt64 JV2_PROP_NM(r,3,expire_timestamp);

@end
