// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/sfelixzhu/Desktop/LBSInfo.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QQWalletLbsGps.h"

@interface QQWalletLbsLBSInfo : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(stGps,setStGps:)) QQWalletLbsGps* JV2_PROP_NM(o,0,stGps);

@end
