// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/sfelixzhu/Desktop/LBSInfo.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QQWalletLbsGpstype.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation QQWalletLbsGpstypeHelper

+ (NSString *)etos:(QQWalletLbsGpstype)e
{
    switch(e){
        case QQWalletLbsGpsWgs84: return @"QQWalletLbsGpsWgs84";
        case QQWalletLbsGpsGcj02: return @"QQWalletLbsGpsGcj02";
        case QQWalletLbsGpsWgsReal: return @"QQWalletLbsGpsWgsReal";
        default: return @"";
    }
}

+ (QQWalletLbsGpstype)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"QQWalletLbsGpsWgs84")) return QQWalletLbsGpsWgs84;
    if(isJceEnumStringEqual(s, @"QQWalletLbsGpsGcj02")) return QQWalletLbsGpsGcj02;
    if(isJceEnumStringEqual(s, @"QQWalletLbsGpsWgsReal")) return QQWalletLbsGpsWgsReal;
    return NSIntegerMin;
}

@end

#endif
