// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/menghuisu/Downloads/jce/WalletConfig.jce'
// **********************************************************************

#import "QQWalletRspWalletConfig.h"

@implementation QQWalletRspWalletConfig

#if JCE_USE_DYNAMIC_PROPERTY
@dynamic JV2_PROP_NM(r,0,result);
@dynamic JV2_PROP_NM(r,1,reqType);
@dynamic JV2_PROP_NM(r,2,seriesNo);
@dynamic JV2_PROP_NM(o,3,refreshType);
@dynamic JV2_PROP_NM(o,4,refreshTime);
@dynamic JV2_PROP_NM(o,5,action);
@dynamic JV2_PROP_NM(o,6,commonMsg);
@dynamic JV2_PROP_EX(o,7,mConfig,M09ONSStringONSString);
#endif

#ifndef JCE_USE_DYNAMIC_INITIALIZATION
- (id)init
{
    if (self = [super init]) {
        JV2_PROP(commonMsg) = DefaultJceString;
    }
    return self;
}
#endif

+ (NSString*)jceType
{
    return @"Style.RspWalletConfig";
}

@end
