// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/menghuisu/Downloads/jce/WalletConfig.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface QQWalletRspWalletConfig : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(result,setResult:)) JceInt32 JV2_PROP_NM(r,0,result);
@property (nonatomic, assign, JV2_PROP_GS_V2(reqType,setReqType:)) JceInt64 JV2_PROP_NM(r,1,reqType);
@property (nonatomic, assign, JV2_PROP_GS_V2(seriesNo,setSeriesNo:)) JceInt64 JV2_PROP_NM(r,2,seriesNo);
@property (nonatomic, assign, JV2_PROP_GS_V2(refreshType,setRefreshType:)) JceInt32 JV2_PROP_NM(o,3,refreshType);
@property (nonatomic, assign, JV2_PROP_GS_V2(refreshTime,setRefreshTime:)) JceInt32 JV2_PROP_NM(o,4,refreshTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(action,setAction:)) JceInt32 JV2_PROP_NM(o,5,action);
@property (nonatomic, retain, JV2_PROP_GS_V2(commonMsg,setCommonMsg:)) NSString* JV2_PROP_NM(o,6,commonMsg);
@property (nonatomic, retain, JV2_PROP_GS_V2(mConfig,setMConfig:)) NSDictionary* JV2_PROP_EX(o,7,mConfig,M09ONSStringONSString);

@end

