// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/sfelixzhu/Desktop/LBSInfo.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QQWalletLbsGpstype.h"

@interface QQWalletLbsGps : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iLat,setILat:)) JceInt32 JV2_PROP_NM(r,0,iLat);
@property (nonatomic, assign, JV2_PROP_GS_V2(iLon,setILon:)) JceInt32 JV2_PROP_NM(r,1,iLon);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAlt,setIAlt:)) JceInt32 JV2_PROP_NM(r,2,iAlt);
@property (nonatomic, assign, JV2_PROP_GS_V2(eType,setEType:)) QQWalletLbsGpstype JV2_PROP_NM(o,3,eType);

@end
