// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/sfelixzhu/Desktop/LBSInfo.jce'
// **********************************************************************

#import "QQWalletLbsGps.h"

@implementation QQWalletLbsGps

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(iLat) = 900000000;
        JV2_PROP(iLon) = 900000000;
        JV2_PROP(iAlt) = -10000000;
        JV2_PROP(eType) = QQWalletLbsGpsWgs84;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"LBS.GPS";
}

@end
