// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/menghuisu/Downloads/jce/WalletConfig.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QQWalletLbsLBSInfo.h"

@interface QQWalletReqWalletConfig : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(reqType,setReqType:)) JceInt64 JV2_PROP_NM(r,0,reqType);
@property (nonatomic, assign, JV2_PROP_GS_V2(uin,setUin:)) JceInt64 JV2_PROP_NM(o,1,uin);
@property (nonatomic, retain, JV2_PROP_GS_V2(platform,setPlatform:)) NSString* JV2_PROP_NM(o,2,platform);
@property (nonatomic, retain, JV2_PROP_GS_V2(version,setVersion:)) NSString* JV2_PROP_NM(o,3,version);
@property (nonatomic, assign, JV2_PROP_GS_V2(iNetType,setINetType:)) JceInt32 JV2_PROP_NM(o,4,iNetType);
@property (nonatomic, retain, JV2_PROP_GS_V2(lbsInfo,setLbsInfo:)) QQWalletLbsLBSInfo* JV2_PROP_NM(o,5,lbsInfo);
@property (nonatomic, assign, JV2_PROP_GS_V2(seriesNo,setSeriesNo:)) JceInt64 JV2_PROP_NM(o,6,seriesNo);
@property (nonatomic, retain, JV2_PROP_GS_V2(commonMsg,setCommonMsg:)) NSString* JV2_PROP_NM(o,7,commonMsg);
@property (nonatomic, retain, JV2_PROP_GS_V2(mParameter,setMParameter:)) NSDictionary* JV2_PROP_EX(o,8,mParameter,M09ONSStringONSString);

@end
