// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/sfelixzhu/Desktop/LBSInfo.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    QQWalletLbsGpsWgs84 = 0,
    QQWalletLbsGpsGcj02 = 1,
    QQWalletLbsGpsWgsReal = 2
};
#define QQWalletLbsGpstype NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface QQWalletLbsGpstypeHelper: JceEnumHelper

+ (NSString *)etos:(QQWalletLbsGpstype)e;
+ (QQWalletLbsGpstype)stoe:(NSString *)s;

@end

#endif
