// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/ResStruct.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStyleFile : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(suffix,setSuffix:)) NSString* JV2_PROP_NM(o,0,suffix);
@property (nonatomic, retain, JV2_PROP_GS_V2(md5,setMd5:)) NSString* JV2_PROP_NM(o,1,md5);

@end
