// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/ResStruct.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface FSStyleCosCredential : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(region,setRegion:)) NSString* JV2_PROP_NM(o,0,region);
@property (nonatomic, retain, JV2_PROP_GS_V2(bucket,setBucket:)) NSString* JV2_PROP_NM(o,1,bucket);
@property (nonatomic, retain, JV2_PROP_GS_V2(path_prefix,setPath_prefix:)) NSString* JV2_PROP_NM(o,2,path_prefix);
@property (nonatomic, retain, JV2_PROP_GS_V2(token,setToken:)) NSString* JV2_PROP_NM(o,3,token);
@property (nonatomic, retain, JV2_PROP_GS_V2(tmp_id,setTmp_id:)) NSString* JV2_PROP_NM(o,4,tmp_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(tmp_key,setTmp_key:)) NSString* JV2_PROP_NM(o,5,tmp_key);
@property (nonatomic, assign, JV2_PROP_GS_V2(expired_time,setExpired_time:)) JceInt64 JV2_PROP_NM(o,6,expired_time);

@end
