// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/ResStruct.jce'
// **********************************************************************

#import "FSStyleCosCredential.h"

@implementation FSStyleCosCredential

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(region) = DefaultJceString;
        JV2_PROP(bucket) = DefaultJceString;
        JV2_PROP(path_prefix) = DefaultJceString;
        JV2_PROP(token) = DefaultJceString;
        JV2_PROP(tmp_id) = DefaultJceString;
        JV2_PROP(tmp_key) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.CosCredential";
}

@end
