// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/ResStruct.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "FSStyleFile.h"

@interface FSStyleApplyUploadReq : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(service_id,setService_id:)) JceInt32 JV2_PROP_NM(o,0,service_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(service_info,setService_info:)) NSDictionary* JV2_PROP_EX(o,1,service_info,M09ONSStringONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(res_type,setRes_type:)) JceInt32 JV2_PROP_NM(o,2,res_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(file_list,setFile_list:)) NSArray* JV2_PROP_EX(o,3,file_list,VOFSStyleFile);
@property (nonatomic, retain, JV2_PROP_GS_V2(reuse_upload_id,setReuse_upload_id:)) NSString* JV2_PROP_NM(o,4,reuse_upload_id);

@end
