// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/ResStruct.jce'
// **********************************************************************

#import "FSStyleApplyUploadRsp.h"

@implementation FSStyleApplyUploadRsp

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(ret_msg) = DefaultJceString;
        JV2_PROP(upload_id) = DefaultJceString;
        JV2_PROP(appid) = DefaultJceString;
        JV2_PROP(video_sign) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.ApplyUploadRsp";
}

@end
