// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/ResStruct.jce'
// **********************************************************************

#import "FSStyleApplyUploadReq.h"

@implementation FSStyleApplyUploadReq

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(reuse_upload_id) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.ApplyUploadReq";
}

@end
